---
abstract: 'Type::Tiny types for GitLab stuff.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Simple: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Types-GitLab
requires:
  Types::Tiny: '1'
  namespace::clean: '0'
  strictures: '0'
resources:
  bugtracker: https://github.com/bluefeet/Types-GitLab/issues
  homepage: https://github.com/bluefeet/Types-GitLab
  repository: https://github.com/bluefeet/Types-GitLab.git
version: '0.01'
